version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home
    ports:
      - 8080:8080
    restart: always
    networks:
      - net
  # remote_host:
  #   container_name: remote-host
  #   image: remote-host
  #   build:
  #     context: ubuntu
  #   networks:
  #     - net
networks:
  net:
